name: Build and deploy staging to GCP
on:
  push:
    branches: [ production ]
jobs:
  deploy:
      uses: codymikol/gcp-deploy/.github/workflows/gcp_bucket_rsync.yml@v1
      with:
        dist_directory: './public'
      secrets:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        bucket_name: ${{ secrets.PRODUCTION_GCP_BUCKET }}
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
